version: '3'
services:
  idos-extension:
    build:
      context: ./go
    ports:
      - 50055:50055
    environment:
      - ETH_RPC_URL=
      - NEAR_RPC_URL=
      - PORT=50055
    restart: on-failure

networks:
  default:
    name: kwil-dev
    external: true
